services:

  auth-service:
    build: ./auth-service
    env_file: ./.env


    expose:
      - "5001"


  item-service:
    build: ./item-service
    env_file: ./.env
    expose:
      - "5002"
    depends_on:
      - auth-service


  client:
    build: ./campus-lost-and-found
    ports:

      - "3000:80"
    depends_on:
      - auth-service
      - item-service